#include "stream_server.h"
#include "camera_app.h"
#include "calibration.h"
#include "img_converters.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include "esp_log.h"
#include "esp_heap_caps.h"
#include "esp_http_server.h"
#include "esp_ota_ops.h"
#include "esp_system.h"
#include "esp_camera.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

static const char *TAG = "stream_server";

static const int DEFAULT_SEGMENTS       = 16;
static const int DEFAULT_DEPTH          = 12;

/* ── pixel helper ──────────────────────────────────────────────────────── */

static inline int clamp_int(int v, int lo, int hi)
{
    return v < lo ? lo : (v > hi ? hi : v);
}

/* ── JSON builder ──────────────────────────────────────────────────────── */

static bool json_append(char *dst, size_t cap, size_t *len, const char *fmt, ...)
{
    if (!dst || !len || *len >= cap) return false;
    va_list ap;
    va_start(ap, fmt);
    int w = vsnprintf(dst + *len, cap - *len, fmt, ap);
    va_end(ap);
    if (w < 0 || (size_t)w >= cap - *len) return false;
    *len += (size_t)w;
    return true;
}

/* ── query-string helpers ───────────────────────────────────────────────── */

/* Parse the full query string into a stack buffer once, then reuse it. */
static int query_buf_get(httpd_req_t *req, char *buf, size_t cap)
{
    size_t qlen = httpd_req_get_url_query_len(req);
    if (!qlen || qlen >= cap) return 0;
    return httpd_req_get_url_query_str(req, buf, qlen + 1) == ESP_OK ? (int)qlen : 0;
}

static int query_int(const char *qbuf, const char *key, int fallback, int lo, int hi)
{
    if (!qbuf || !qbuf[0]) return fallback;
    char param[16] = {0};
    if (httpd_query_key_value(qbuf, key, param, sizeof(param)) != ESP_OK) return fallback;
    return clamp_int(atoi(param), lo, hi);
}

/* ── calibration JSON parser ────────────────────────────────────────────── */

/*
 * Finds "key":{"x":N,"y":N} in a JSON string and extracts N for x and y.
 * Operates on the canonical JSON format generated by JSON.stringify().
 */
static bool parse_corner(const char *json, const char *key,
                          int16_t *x, int16_t *y)
{
    /* Build search token, e.g. "\"tl\"" */
    char tok[8];
    snprintf(tok, sizeof(tok), "\"%s\"", key);

    const char *p = strstr(json, tok);
    if (!p) return false;

    p = strstr(p, "\"x\"");
    if (!p) return false;
    p = strchr(p, ':');
    if (!p) return false;
    *x = (int16_t)atoi(p + 1);

    p = strstr(p, "\"y\"");
    if (!p) return false;
    p = strchr(p, ':');
    if (!p) return false;
    *y = (int16_t)atoi(p + 1);

    return true;
}

/* ── calibrated edge strip sampler ─────────────────────────────────────── */

/*
 * Walk along the edge from (ax,ay) to (bx,by), and at each point sample
 * `depth` pixels toward (cent_x, cent_y).  All arithmetic is integer-only.
 *
 * The "inward step" is computed by normalising (centroid - edge_point) so
 * that the dominant axis advances 1 pixel per step, and the minor axis
 * advances proportionally.  This gives correct behaviour for all four
 * edges of an arbitrary (possibly skewed) quadrilateral.
 */
static void sample_edge_strip(
    const uint8_t *rgb, int W, int H,
    int ax, int ay, int bx, int by,
    int cent_x, int cent_y, int depth,
    long long *sum_r, long long *sum_g, long long *sum_b, int *count)
{
    int edx = bx - ax;
    int edy = by - ay;
    int n   = (abs(edx) > abs(edy) ? abs(edx) : abs(edy));
    if (n == 0) n = 1;

    for (int i = 0; i <= n; i++) {
        int ex = ax + edx * i / n;
        int ey = ay + edy * i / n;

        int idx   = cent_x - ex;
        int idy   = cent_y - ey;
        int idist = (abs(idx) > abs(idy) ? abs(idx) : abs(idy));
        if (idist == 0) continue;

        for (int d = 0; d < depth; d++) {
            int px = ex + idx * d / idist;
            int py = ey + idy * d / idist;
            if (px < 0 || px >= W || py < 0 || py >= H) break;
            int off = (py * W + px) * 3;
            *sum_r += rgb[off];
            *sum_g += rgb[off + 1];
            *sum_b += rgb[off + 2];
            (*count)++;
        }
    }
}

/* ═══════════════════════════════════════════════════════════════════════════
   HTTP handlers
   ═══════════════════════════════════════════════════════════════════════════ */

/* GET / ------------------------------------------------------------------ */

static const char ROOT_HTML[] =
    "<!DOCTYPE html><html><head>"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<title>Ambilight Cal</title>"
    "<style>"
    "body{font-family:sans-serif;max-width:960px;margin:20px auto;padding:0 12px;"
         "background:#111;color:#eee}"
    "h1{margin:8px 0}"
    ".ctrl{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}"
    "button{padding:8px 14px;font-size:15px;cursor:pointer;border-radius:4px;"
           "border:none;background:#4a90d9;color:#fff}"
    "#saveBtn{background:#27ae60}"
    "#clrBtn{background:#c0392b}"
    "button:disabled{opacity:.5;cursor:not-allowed}"
    "#st{font-size:14px;color:#aaa;min-height:20px;margin:6px 0}"
    "#wrap{overflow:auto;border:2px solid #555;max-height:76vh}"
    "canvas{display:block;cursor:crosshair}"
    "input[type=range]{vertical-align:middle}"
    "</style></head><body>"
    "<h1>Ambilight Calibration</h1>"
    "<div class='ctrl'>"
      "<button id='capBtn'>Capture</button>"
      "<button id='saveBtn' disabled>Save Corners</button>"
      "<button id='clrBtn'>Reset</button>"
      "<label style='font-size:14px;color:#ccc'>Zoom "
        "<span id='zl'>100</span>% "
        "<input type='range' min='50' max='200' value='100' id='zs' style='width:130px'>"
      "</label>"
      "<label style='font-size:14px;color:#ccc'>Exp "
        "<span id='el'>30</span> "
        "<input type='range' min='0' max='300' value='30' id='es' style='width:130px'>"
      "</label>"
      "<label style='font-size:14px;color:#ccc'>Quality "
        "<span id='ql'>30</span> "
        "<input type='range' min='10' max='63' value='30' id='qs' style='width:130px'>"
        "<span style='font-size:11px;color:#666'> (10=best 63=fastest)</span>"
      "</label>"
      "<label style='font-size:14px;color:#ccc'>Size "
        "<select id='sz' style='background:#222;color:#eee;border:1px solid #555;padding:4px'>"
          "<option value='5'>QVGA 320x240 (fastest)</option>"
          "<option value='6'>CIF  400x296</option>"
          "<option value='8' selected>VGA  640x480</option>"
          "<option value='9'>SVGA 800x600</option>"
          "<option value='10'>XGA 1024x768</option>"
        "</select>"
      "</label>"
    "</div>"
    "<div id='st'>Press Capture, then click: TL &rarr; TR &rarr; BR &rarr; BL</div>"
    "<div id='wrap'><canvas id='C'></canvas></div>"
    "<script>"
    "const LBL=['TL','TR','BR','BL'];"
    "const CLR=['#f55','#5f5','#55f','#ff5'];"
    "let corners=[],imgEl=null;"
    "const cv=document.getElementById('C');"
    "const gc=cv.getContext('2d');"
    "const st=document.getElementById('st');"
    "const sv=document.getElementById('saveBtn');"
    "const zs=document.getElementById('zs');"
    "const zl=document.getElementById('zl');"
    "function applyZoom(){"
      "const z=parseInt(zs.value)/100;"
      "zl.textContent=zs.value;"
      "if(imgEl){"
        "cv.style.width=(imgEl.naturalWidth*z)+'px';"
        "cv.style.height=(imgEl.naturalHeight*z)+'px';"
      "}"
    "}"
    "zs.oninput=applyZoom;"

    "let _expT,_qlT;"
    "const es=document.getElementById('es');"
    "const el=document.getElementById('el');"
    "es.oninput=()=>{"
      "el.textContent=es.value;"
      "clearTimeout(_expT);"
      "_expT=setTimeout(()=>fetch('/settings?exp='+es.value),300);"
    "};"

    "const qs=document.getElementById('qs');"
    "const ql=document.getElementById('ql');"
    "qs.oninput=()=>{"
      "ql.textContent=qs.value;"
      "clearTimeout(_qlT);"
      "_qlT=setTimeout(()=>fetch('/settings?quality='+qs.value),300);"
    "};"

    "document.getElementById('sz').onchange=function(){"
      "fetch('/settings?size='+this.value);"
    "};"

    "function draw(){"
      "if(!imgEl)return;"
      "gc.drawImage(imgEl,0,0,cv.width,cv.height);"
      "if(corners.length===4){"
        "gc.beginPath();"
        "gc.moveTo(corners[0].x,corners[0].y);"
        "for(let i=1;i<4;i++)gc.lineTo(corners[i].x,corners[i].y);"
        "gc.closePath();"
        "gc.strokeStyle='rgba(255,255,255,0.35)';"
        "gc.lineWidth=1;"
        "gc.setLineDash([6,4]);"
        "gc.stroke();"
        "gc.setLineDash([]);"
      "}"
      "corners.forEach((c,i)=>{"
        "gc.beginPath();gc.arc(c.x,c.y,14,0,Math.PI*2);"
        "gc.fillStyle=CLR[i]+'44';gc.fill();"
        "gc.strokeStyle=CLR[i];gc.lineWidth=2;gc.stroke();"
        "gc.fillStyle='#fff';gc.font='bold 12px sans-serif';"
        "gc.textAlign='center';gc.textBaseline='middle';"
        "gc.fillText(LBL[i],c.x,c.y);"
      "});"
    "}"

    "cv.addEventListener('click',e=>{"
      "if(!imgEl||corners.length>=4)return;"
      "const r=cv.getBoundingClientRect();"
      "const sx=cv.width/r.width,sy=cv.height/r.height;"
      "corners.push({x:Math.round((e.clientX-r.left)*sx),"
                    "y:Math.round((e.clientY-r.top)*sy)});"
      "draw();"
      "if(corners.length<4){"
        "st.textContent='Click: '+LBL[corners.length];"
      "}else{"
        "st.textContent='All 4 corners set. Press Save.';"
        "sv.disabled=false;"
      "}"
    "});"

    "document.getElementById('capBtn').onclick=()=>{"
      "st.textContent='Capturing...';"
      "const img=new Image();"
      "img.onload=()=>{"
        "imgEl=img;"
        "cv.width=img.naturalWidth;cv.height=img.naturalHeight;"
        "corners=[];sv.disabled=true;"
        "applyZoom();"
        "draw();"
        "st.textContent='Click: '+LBL[0];"
      "};"
      "img.onerror=()=>st.textContent='Capture failed!';"
      "img.src='/jpg?t='+Date.now();"
    "};"

    "document.getElementById('clrBtn').onclick=()=>{"
      "corners=[];sv.disabled=true;draw();"
      "st.textContent=imgEl?'Click: '+LBL[0]:'Press Capture first.';"
    "};"

    "sv.onclick=async()=>{"
      "if(corners.length!==4)return;"
      "const body=JSON.stringify({tl:corners[0],tr:corners[1],"
                                  "br:corners[2],bl:corners[3]});"
      "try{"
        "const r=await fetch('/calibration',"
          "{method:'POST',headers:{'Content-Type':'application/json'},body});"
        "st.textContent=r.ok?'Saved!':'Save failed: '+r.status;"
      "}catch(e){st.textContent='Error: '+e.message;}"
    "};"

    /* Load existing calibration on page open */
    "fetch('/calibration').then(r=>r.json()).then(d=>{"
      "if(d.valid){"
        "corners=[d.tl,d.tr,d.br,d.bl];"
        "sv.disabled=false;"
        "st.textContent='Calibration loaded. Capture to view on image.';"
      "}"
    "}).catch(()=>{});"
    "</script>"
    "<p style='margin-top:16px;font-size:13px;color:#666'>"
      "<a href='/ota' style='color:#888'>Firmware update (OTA)</a>"
    "</p>"
    "</body></html>";

static esp_err_t root_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html");
    return httpd_resp_send(req, ROOT_HTML, HTTPD_RESP_USE_STRLEN);
}

/* GET /jpg --------------------------------------------------------------- */

static esp_err_t jpg_handler(httpd_req_t *req)
{
    /* GRAB_WHEN_EMPTY: the buffer holds the previous frame. Flush it to
     * trigger a fresh DMA capture, then block on the new frame. */
    camera_fb_t *stale = camera_app_get_frame();
    if (stale) {
        camera_app_return_frame(stale);
    } else {
        if (camera_app_recover() != ESP_OK) {
            httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR,
                                "Camera recovery failed");
            return ESP_FAIL;
        }
    }

    camera_fb_t *fb = camera_app_get_frame();
    if (!fb) {
        if (camera_app_recover() == ESP_OK) fb = camera_app_get_frame();
        if (!fb) {
            httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR,
                                "Camera capture failed");
            return ESP_FAIL;
        }
    }

    /* OV2640 hardware JPEG — frame buffer is already a JPEG, send directly. */
    httpd_resp_set_type(req, "image/jpeg");
    httpd_resp_set_hdr(req, "Cache-Control", "no-store, no-cache, must-revalidate");
    esp_err_t res = httpd_resp_send(req, (const char *)fb->buf, (ssize_t)fb->len);
    camera_app_return_frame(fb);
    return res;
}

/* GET /calibration ------------------------------------------------------- */

static esp_err_t calibration_get_handler(httpd_req_t *req)
{
    calibration_t cal = calibration_get();
    char buf[200];
    int n;
    if (cal.valid) {
        n = snprintf(buf, sizeof(buf),
            "{\"valid\":true,"
            "\"tl\":{\"x\":%d,\"y\":%d},"
            "\"tr\":{\"x\":%d,\"y\":%d},"
            "\"br\":{\"x\":%d,\"y\":%d},"
            "\"bl\":{\"x\":%d,\"y\":%d}}",
            cal.tl.x, cal.tl.y,
            cal.tr.x, cal.tr.y,
            cal.br.x, cal.br.y,
            cal.bl.x, cal.bl.y);
    } else {
        n = snprintf(buf, sizeof(buf), "{\"valid\":false}");
    }
    httpd_resp_set_type(req, "application/json");
    return httpd_resp_send(req, buf, n);
}

/* POST /calibration ------------------------------------------------------ */

static esp_err_t calibration_post_handler(httpd_req_t *req)
{
    if (req->content_len == 0 || req->content_len > 254) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Bad body length");
        return ESP_FAIL;
    }
    char body[255] = {0};
    int  got = httpd_req_recv(req, body, req->content_len);
    if (got <= 0) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Receive failed");
        return ESP_FAIL;
    }

    calibration_t cal = {0};
    if (!parse_corner(body, "tl", &cal.tl.x, &cal.tl.y) ||
        !parse_corner(body, "tr", &cal.tr.x, &cal.tr.y) ||
        !parse_corner(body, "br", &cal.br.x, &cal.br.y) ||
        !parse_corner(body, "bl", &cal.bl.x, &cal.bl.y)) {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "JSON parse error");
        return ESP_FAIL;
    }
    cal.valid = true;

    if (calibration_save(&cal) != ESP_OK) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Save failed");
        return ESP_FAIL;
    }
    httpd_resp_set_type(req, "application/json");
    return httpd_resp_sendstr(req, "{\"ok\":true}");
}

/* GET /edges ------------------------------------------------------------- */

static esp_err_t edge_handler(httpd_req_t *req)
{
    camera_fb_t *fb = camera_app_get_frame();
    if (!fb) {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR,
                            "Camera capture failed");
        return ESP_FAIL;
    }
    if (fb->format != PIXFORMAT_JPEG) {
        camera_app_return_frame(fb);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR,
                            "Expected JPEG format");
        return ESP_FAIL;
    }

    const int W        = (int)fb->width;
    const int H        = (int)fb->height;
    char qbuf[64];
    query_buf_get(req, qbuf, sizeof(qbuf));
    const int segments = query_int(qbuf, "segments", DEFAULT_SEGMENTS, 4, 64);
    const int depth    = query_int(qbuf, "depth",    DEFAULT_DEPTH,    2, 48);

    /* Decode hardware JPEG to RGB888 in PSRAM so we can sample pixels. */
    uint8_t *rgb = heap_caps_malloc((size_t)W * H * 3,
                                    MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    if (!rgb) {
        camera_app_return_frame(fb);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OOM for decode");
        return ESP_FAIL;
    }
    bool decoded = fmt2rgb888(fb->buf, fb->len, PIXFORMAT_JPEG, rgb);
    camera_app_return_frame(fb);    /* release JPEG buffer as soon as decode is done */

    if (!decoded) {
        free(rgb);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "JPEG decode failed");
        return ESP_FAIL;
    }

    const calibration_t cal = calibration_get();

    const int cent_x = cal.valid
        ? ((int)cal.tl.x + cal.tr.x + cal.br.x + cal.bl.x) / 4
        : W / 2;
    const int cent_y = cal.valid
        ? ((int)cal.tl.y + cal.tr.y + cal.br.y + cal.bl.y) / 4
        : H / 2;

    size_t cap  = 512 + (size_t)segments * 4 * 40;
    char  *json = malloc(cap);
    if (!json) {
        free(rgb);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OOM");
        return ESP_FAIL;
    }

    size_t n = 0;
    if (!json_append(json, cap, &n,
            "{\"calibrated\":%s,\"width\":%d,\"height\":%d,"
            "\"segments_per_edge\":%d,\"sample_depth\":%d,\"edges\":{",
            cal.valid ? "true" : "false", W, H, segments, depth)) {
        goto fail;
    }

    static const char *const edge_names[4] = {"top", "right", "bottom", "left"};

    for (int edge = 0; edge < 4; edge++) {
        if (!json_append(json, cap, &n, "\"%s\":[", edge_names[edge])) goto fail;

        for (int s = 0; s < segments; s++) {
            long long sum_r = 0, sum_g = 0, sum_b = 0;
            int       count = 0;

            if (cal.valid) {
                int ax, ay, bx, by;
                switch (edge) {
                    case 0: /* top:    TL -> TR */
                        ax = cal.tl.x + (cal.tr.x - cal.tl.x) *  s      / segments;
                        ay = cal.tl.y + (cal.tr.y - cal.tl.y) *  s      / segments;
                        bx = cal.tl.x + (cal.tr.x - cal.tl.x) * (s + 1) / segments;
                        by = cal.tl.y + (cal.tr.y - cal.tl.y) * (s + 1) / segments;
                        break;
                    case 1: /* right:  TR -> BR */
                        ax = cal.tr.x + (cal.br.x - cal.tr.x) *  s      / segments;
                        ay = cal.tr.y + (cal.br.y - cal.tr.y) *  s      / segments;
                        bx = cal.tr.x + (cal.br.x - cal.tr.x) * (s + 1) / segments;
                        by = cal.tr.y + (cal.br.y - cal.tr.y) * (s + 1) / segments;
                        break;
                    case 2: /* bottom: BL -> BR */
                        ax = cal.bl.x + (cal.br.x - cal.bl.x) *  s      / segments;
                        ay = cal.bl.y + (cal.br.y - cal.bl.y) *  s      / segments;
                        bx = cal.bl.x + (cal.br.x - cal.bl.x) * (s + 1) / segments;
                        by = cal.bl.y + (cal.br.y - cal.bl.y) * (s + 1) / segments;
                        break;
                    default: /* left:  TL -> BL */
                        ax = cal.tl.x + (cal.bl.x - cal.tl.x) *  s      / segments;
                        ay = cal.tl.y + (cal.bl.y - cal.tl.y) *  s      / segments;
                        bx = cal.tl.x + (cal.bl.x - cal.tl.x) * (s + 1) / segments;
                        by = cal.tl.y + (cal.bl.y - cal.tl.y) * (s + 1) / segments;
                        break;
                }
                sample_edge_strip(rgb, W, H, ax, ay, bx, by,
                                  cent_x, cent_y, depth,
                                  &sum_r, &sum_g, &sum_b, &count);
            } else {
                /* Uncalibrated: sample a rectangular strip along the raw image edge */
                if (edge == 0 || edge == 2) { /* top / bottom */
                    int x0 =  s      * W / segments;
                    int x1 = (s + 1) * W / segments;
                    int y0 = (edge == 0) ? 0     : H - depth;
                    int y1 = (edge == 0) ? depth : H;
                    y0 = clamp_int(y0, 0, H);
                    y1 = clamp_int(y1, 0, H);
                    for (int y = y0; y < y1; y++) {
                        for (int x = x0; x < x1; x++) {
                            int off = (y * W + x) * 3;
                            sum_r += rgb[off]; sum_g += rgb[off+1]; sum_b += rgb[off+2]; count++;
                        }
                    }
                } else { /* right / left */
                    int y0 =  s      * H / segments;
                    int y1 = (s + 1) * H / segments;
                    int x0 = (edge == 1) ? W - depth : 0;
                    int x1 = (edge == 1) ? W         : depth;
                    x0 = clamp_int(x0, 0, W);
                    x1 = clamp_int(x1, 0, W);
                    for (int y = y0; y < y1; y++) {
                        for (int x = x0; x < x1; x++) {
                            int off = (y * W + x) * 3;
                            sum_r += rgb[off]; sum_g += rgb[off+1]; sum_b += rgb[off+2]; count++;
                        }
                    }
                }
            }

            int avg_r = count > 0 ? (int)(sum_r / count) : 0;
            int avg_g = count > 0 ? (int)(sum_g / count) : 0;
            int avg_b = count > 0 ? (int)(sum_b / count) : 0;

            if (!json_append(json, cap, &n, "%s{\"r\":%d,\"g\":%d,\"b\":%d}",
                             s == 0 ? "" : ",", avg_r, avg_g, avg_b)) {
                goto fail;
            }
        }

        if (!json_append(json, cap, &n, "]%s", edge == 3 ? "" : ",")) goto fail;
    }

    if (!json_append(json, cap, &n, "}}\n")) goto fail;
    free(rgb);

    httpd_resp_set_type(req, "application/json");
    esp_err_t res = httpd_resp_send(req, json, (ssize_t)n);
    free(json);
    return res;

fail:
    free(rgb);
    free(json);
    httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "JSON build failed");
    return ESP_FAIL;
}

/* GET /settings?exp=N&quality=N -------------------------------------------- */

static esp_err_t settings_handler(httpd_req_t *req)
{
    char qbuf[64];
    query_buf_get(req, qbuf, sizeof(qbuf));
    int exp     = query_int(qbuf, "exp",     -1,  0, 1200);
    int quality = query_int(qbuf, "quality", -1, 10,   63);
    int size    = query_int(qbuf, "size",    -1,  0,   13);
    sensor_t *s = esp_camera_sensor_get();
    if (s) {
        if (exp >= 0)     { s->set_aec_value(s, exp);                        ESP_LOGI(TAG, "Exposure %d", exp); }
        if (quality >= 0) { s->set_quality(s, quality);                       ESP_LOGI(TAG, "Quality %d", quality); }
        if (size >= 0)    { s->set_framesize(s, (framesize_t)size);           ESP_LOGI(TAG, "Framesize %d", size); }
    }
    char buf[64];
    int n = snprintf(buf, sizeof(buf), "{\"exp\":%d,\"quality\":%d,\"size\":%d}",
                     exp, quality, size);
    httpd_resp_set_type(req, "application/json");
    return httpd_resp_send(req, buf, n);
}

/* GET /ota ----------------------------------------------------------------- */

static const char OTA_HTML[] =
    "<!DOCTYPE html><html><head>"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<title>OTA Update</title>"
    "<style>"
    "body{font-family:sans-serif;max-width:520px;margin:40px auto;padding:0 16px;"
         "background:#111;color:#eee}"
    "h1{margin:8px 0}"
    "input{margin:12px 0;display:block;color:#eee;width:100%}"
    "button{padding:10px 20px;background:#e67e22;color:#fff;border:none;"
           "border-radius:4px;cursor:pointer;font-size:15px}"
    "button:disabled{opacity:.5;cursor:not-allowed}"
    "progress{width:100%;height:18px;margin-top:10px;display:none}"
    "#st{margin-top:12px;color:#aaa}"
    "a{color:#888}"
    "</style></head><body>"
    "<h1>OTA Firmware Update</h1>"
    "<p>Select <code>build/esp32_cam_test.bin</code> then press Flash.</p>"
    "<input type='file' id='f' accept='.bin'>"
    "<button id='btn' onclick='upload()'>Flash</button>"
    "<progress id='pg'></progress>"
    "<div id='st'>Ready.</div>"
    "<p><a href='/'>&#8592; Back to calibration</a></p>"
    "<script>"
    "function upload(){"
      "const file=document.getElementById('f').files[0];"
      "if(!file){alert('Select a .bin file first');return;}"
      "const st=document.getElementById('st');"
      "const pg=document.getElementById('pg');"
      "const btn=document.getElementById('btn');"
      "pg.style.display='block';pg.max=file.size;pg.value=0;"
      "btn.disabled=true;"
      "st.textContent='Uploading\u2026';"
      "const xhr=new XMLHttpRequest();"
      "xhr.open('POST','/ota');"
      "xhr.upload.onprogress=e=>{"
        "pg.value=e.loaded;"
        "st.textContent=Math.round(e.loaded/e.total*100)+'%';"
      "};"
      "xhr.onload=()=>{"
        "st.textContent=xhr.status===200"
          "?'Done! Device is rebooting\u2026'"
          ":'Error: '+xhr.responseText;"
        "btn.disabled=false;"
      "};"
      "xhr.onerror=()=>{"
        "st.textContent='Network error \u2014 device may have rebooted.';"
        "btn.disabled=false;"
      "};"
      "xhr.send(file);"
    "}"
    "</script></body></html>";

static esp_err_t ota_get_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html");
    return httpd_resp_send(req, OTA_HTML, HTTPD_RESP_USE_STRLEN);
}

/* POST /ota ---------------------------------------------------------------- */

static esp_err_t ota_post_handler(httpd_req_t *req)
{
    ESP_LOGI(TAG, "OTA start, image size: %d bytes", req->content_len);

    const esp_partition_t *target = esp_ota_get_next_update_partition(NULL);
    if (!target) {
        ESP_LOGE(TAG, "No OTA partition found");
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR,
                            "No OTA partition — re-flash with USB first");
        return ESP_FAIL;
    }
    ESP_LOGI(TAG, "Writing to partition: %s at 0x%08lx", target->label, target->address);

    esp_ota_handle_t handle;
    esp_err_t err = esp_ota_begin(target, OTA_WITH_SEQUENTIAL_WRITES, &handle);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "esp_ota_begin: %s", esp_err_to_name(err));
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OTA begin failed");
        return ESP_FAIL;
    }

    char *buf = malloc(4096);
    if (!buf) {
        esp_ota_abort(handle);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OOM");
        return ESP_FAIL;
    }

    int remaining = req->content_len;
    while (remaining > 0) {
        int want = remaining < 4096 ? remaining : 4096;
        int got  = httpd_req_recv(req, buf, want);
        if (got <= 0) {
            if (got == HTTPD_SOCK_ERR_TIMEOUT) continue;
            ESP_LOGE(TAG, "Receive error: %d", got);
            free(buf); esp_ota_abort(handle);
            httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Receive failed");
            return ESP_FAIL;
        }
        err = esp_ota_write(handle, buf, got);
        if (err != ESP_OK) {
            ESP_LOGE(TAG, "esp_ota_write: %s", esp_err_to_name(err));
            free(buf); esp_ota_abort(handle);
            httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Flash write failed");
            return ESP_FAIL;
        }
        remaining -= got;
    }
    free(buf);

    err = esp_ota_end(handle);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "esp_ota_end: %s", esp_err_to_name(err));
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR,
                            "OTA validation failed — wrong image?");
        return ESP_FAIL;
    }

    err = esp_ota_set_boot_partition(target);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "esp_ota_set_boot_partition: %s", esp_err_to_name(err));
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Set boot partition failed");
        return ESP_FAIL;
    }

    ESP_LOGI(TAG, "OTA success — rebooting");
    httpd_resp_sendstr(req, "OTA OK — rebooting");
    vTaskDelay(pdMS_TO_TICKS(500));
    esp_restart();
    return ESP_OK;
}

/* ═══════════════════════════════════════════════════════════════════════════
   Server startup
   ═══════════════════════════════════════════════════════════════════════════ */

esp_err_t stream_server_start(void)
{
    httpd_config_t config   = HTTPD_DEFAULT_CONFIG();
    config.stack_size        = 8192;   /* OTA handler needs more than the default 4 KB */
    config.recv_wait_timeout = 30;     /* allow slow WiFi during large OTA upload       */
    config.send_wait_timeout = 30;
    config.max_uri_handlers  = 10;
    config.core_id           = 1;      /* APP_CPU: keep PRO_CPU (core 0) free for WiFi  */
    config.lru_purge_enable  = true;   /* reclaim stale sockets so new requests aren't blocked */
    httpd_handle_t server = NULL;

    if (httpd_start(&server, &config) != ESP_OK) {
        ESP_LOGE(TAG, "Failed to start HTTP server");
        return ESP_FAIL;
    }

    const httpd_uri_t uris[] = {
        { .uri = "/",            .method = HTTP_GET,  .handler = root_handler,
          .user_ctx = NULL },
        { .uri = "/jpg",         .method = HTTP_GET,  .handler = jpg_handler,
          .user_ctx = NULL },
        { .uri = "/calibration", .method = HTTP_GET,  .handler = calibration_get_handler,
          .user_ctx = NULL },
        { .uri = "/calibration", .method = HTTP_POST, .handler = calibration_post_handler,
          .user_ctx = NULL },
        { .uri = "/edges",       .method = HTTP_GET,  .handler = edge_handler,
          .user_ctx = NULL },
        { .uri = "/ota",         .method = HTTP_GET,  .handler = ota_get_handler,
          .user_ctx = NULL },
        { .uri = "/ota",         .method = HTTP_POST, .handler = ota_post_handler,
          .user_ctx = NULL },
        { .uri = "/settings",    .method = HTTP_GET,  .handler = settings_handler,
          .user_ctx = NULL },
    };

    for (size_t i = 0; i < sizeof(uris) / sizeof(uris[0]); i++) {
        httpd_register_uri_handler(server, &uris[i]);
    }

    ESP_LOGI(TAG, "HTTP server started on port %d", config.server_port);
    return ESP_OK;
}
